# Generated by Django 4.1.3 on 2022-12-13 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roombooking', '0002_alter_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
