# Generated by Django 4.1.3 on 2022-12-13 03:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('roombooking', '0003_alter_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this booking', primary_key=True, serialize=False),
        ),
    ]
