# Generated by Django 4.1.3 on 2022-12-14 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roombooking', '0004_alter_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='enddate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='startdate',
            field=models.DateField(),
        ),
    ]
