# Generated by Django 4.1.3 on 2022-12-16 02:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roombooking', '0006_alter_booking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='endtime',
            field=models.TimeField(default=datetime.datetime(2022, 12, 16, 10, 37, 4, 36019)),
        ),
        migrations.AddField(
            model_name='booking',
            name='starttime',
            field=models.TimeField(default=datetime.datetime(2022, 12, 16, 10, 37, 4, 36019)),
        ),
    ]
