# Generated by Django 4.1.3 on 2022-12-16 02:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roombooking', '0007_booking_endtime_booking_starttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='endtime',
            field=models.TimeField(default=datetime.datetime(2022, 12, 16, 10, 38, 23, 607072)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='starttime',
            field=models.TimeField(default=datetime.datetime(2022, 12, 16, 10, 38, 23, 607072)),
        ),
    ]
