# Generated by Django 4.1.3 on 2022-12-16 03:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roombooking', '0008_alter_booking_endtime_alter_booking_starttime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(choices=[('08:00 AM', '08:00 AM'), ('09:00 AM', '09:00 AM'), ('10:00 AM', '10:00 AM'), ('11:00 AM', '11:00 AM'), ('12:00 PM', '12:00 PM'), ('01:00 PM', '01:00 PM'), ('02:00 PM', '02:00 PM')])),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='endtime',
            field=models.TimeField(default=datetime.datetime(2022, 12, 16, 11, 39, 25, 234600)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='starttime',
            field=models.TimeField(default=datetime.datetime(2022, 12, 16, 11, 39, 25, 234600)),
        ),
    ]
