# Generated by Django 4.1.3 on 2022-12-16 03:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roombooking', '0009_time_alter_booking_endtime_alter_booking_starttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='endtime',
            field=models.TimeField(default=datetime.datetime(2022, 12, 16, 11, 41, 48, 840498)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='starttime',
            field=models.TimeField(default=datetime.datetime(2022, 12, 16, 11, 41, 48, 840498)),
        ),
        migrations.AlterField(
            model_name='time',
            name='time',
            field=models.TimeField(),
        ),
    ]
