# Generated by Django 4.1.3 on 2022-12-16 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roombooking', '0010_alter_booking_endtime_alter_booking_starttime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='endtime',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='starttime',
        ),
    ]
