# Generated by Django 4.1.3 on 2022-12-16 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roombooking', '0011_remove_booking_endtime_remove_booking_starttime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Time',
        ),
    ]
