# Generated by Django 4.1.3 on 2022-12-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roombooking', '0013_endtime_starttime_booking_endtime_booking_starttime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-dateadded']},
        ),
        migrations.AddField(
            model_name='room',
            name='room_pic',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
